name: JestemGraczem
description: Oficjalny plugin serwerow JestemGraczem.pl
version: '1.0'
main: com.idkcloud.JestemGraczem.JestemGraczem
author: otlet
website: idkcloud.com
api-version: '1.14'
depend:
  - WorldEdit
  - WorldGuard
  - WorldGuardEvents
  - Vault
commands:
  setdeathspawn:
    description: Set Death Spawn
    aliases:
      - setdeathjail
    permission: jg.setdeathspawn
    permission-message: Tylko KRUL KORWIN moze ustawic deathspawn!
    usage: /setdeathspawn
  randomtp:
    description: Use Random Teleportation
    aliases:
      - rtp
      - wild
    permission: jg.randomtp
    permission-message: Nie umiesz w teleportację!
    usage: /randomtp
permissions:
  jg.admin:
    description: Komendy admendy!
    default: op
  jg.randomtp:
    description: Komendy admendy!
    default: op